### ISSUE TITLE
generic-pool _waitingClients size has been growing

### ISSUE THREAD

**Issue by kuake** [exposebox/node-thrift2-hbase#4]
like:
```
hbasePool.acquire(function(err, hbaseClient){
    //**Shortly after the start can not executed here**
});
```
Shortly after the start, I can't put anything to hbase
and I find generic-pool _waitingClients size has been growing.
How to find the problem?
Thanks for your reply

**Comment by moshewe** [comment]
Can you supply the exact code you were using?
Did you use `require('node-thrift2-hbase')(config)` or some internal file within the library?

**Comment by kuake** [comment]
yes,
```
var hbase = require('node-thrift2-hbase');
var config = {
  hosts: ['127.0.0.1'],
  port: 8000
};
var hbaseService = hbase(config);
var hbasePool = hbaseService.clientPool;
```
if i use once like:
```
hbasePool.acquire(function(err, hbaseClient){
    //**works ok**
});
```
it works ok, but on-line use
```
hbasePool.acquire(function(err, hbaseClient){
    //**Shortly after the start can not executed here**
});
```
Can not find the problem
Could you help me how to find the problem?
Thanks very much

**Comment by kuake** [comment]
sory, new code forget to 
``` hbasePool.release(hbaseClient); ```

**Comment by kuake** [comment]
do you plan to update generic-pool to 3.x ?

**Comment by moshewe** [comment]
Exactly in order to avoid this issue, we've implemented functions that perform HBase queries for you, so you won't have to handle the client directly - `scan`, `getRow`, `incRow` and `putRow`. The client pool is there for the internal implementation of these functions. I'll update the usage examples to reflect this change.

You are welcome to update generic-pool to 3.x and make a pull request :-) Do you see any significant gain to be had by updating that library?
